# Generated by Django 5.0.3 on 2024-03-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
